-- Custom Database Setup Example
-- This demonstrates how to set up your own database schema in Supabase

-- Create a custom schema for your application
create schema if not exists app;

-- Create a custom users table with additional fields
create table app.user_profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  bio text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table app.user_profiles enable row level security;

-- Create policies for user_profiles
create policy "Public profiles are viewable by everyone." 
  on app.user_profiles for select 
  using ( true );

create policy "Users can insert their own profile." 
  on app.user_profiles for insert 
  with check ( auth.uid() = id );

create policy "Users can update own profile." 
  on app.user_profiles for update 
  using ( auth.uid() = id );

-- Create a custom posts table
create table app.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  title text not null,
  content text,
  slug text unique,
  published boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for posts
alter table app.posts enable row level security;

-- Create policies for posts
create policy "Published posts are viewable by everyone." 
  on app.posts for select 
  using ( published = true );

create policy "Users can view their own posts." 
  on app.posts for select 
  using ( auth.uid() = user_id );

create policy "Users can insert their own posts." 
  on app.posts for insert 
  with check ( auth.uid() = user_id );

create policy "Users can update their own posts." 
  on app.posts for update 
  using ( auth.uid() = user_id );

-- Create a function to handle updated_at timestamps
create or replace function app.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- Create triggers for updated_at
create trigger handle_updated_at before update on app.user_profiles
  for each row execute procedure app.handle_updated_at();

create trigger handle_updated_at before update on app.posts
  for each row execute procedure app.handle_updated_at();

-- Create indexes for better performance
create index user_profiles_username_idx on app.user_profiles (username);
create index posts_user_id_idx on app.posts (user_id);
create index posts_slug_idx on app.posts (slug);
create index posts_published_idx on app.posts (published);

-- Grant permissions
grant usage on schema app to anon, authenticated;
grant all on all tables in schema app to anon, authenticated;
grant all on all sequences in schema app to anon, authenticated;
